package com.wynndie.spwallet.sharedCore.presentation.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF8B5CB5)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE8DEF0)
val onPrimaryContainerLight = Color(0xFF8B5CB5)
val secondaryLight = Color(0xFF596DC7)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDEE2F4)
val onSecondaryContainerLight = Color(0xFF596DC7)
val tertiaryLight = Color(0xFFB85234)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF1DCD6)
val onTertiaryContainerLight = Color(0xFFB85234)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFFBA1A1A)
val backgroundLight = Color(0xFFFDFCFE)
val onBackgroundLight = Color(0xFF1C1B20)
val surfaceLight = Color(0xFFFDFCFE)
val onSurfaceLight = Color(0xFF1A1A1A)
val surfaceVariantLight = Color(0xFFE5E1EC)
val onSurfaceVariantLight = Color(0xFF4D4D4D)
val outlineLight = Color(0xFFA6A6A6)
val outlineVariantLight = Color(0xFFD9D9D9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313036)
val inverseOnSurfaceLight = Color(0xFFF3EFF7)
val inversePrimaryLight = Color(0xFFC5C0FF)
val surfaceDimLight = Color(0xFFDCD8E0)
val surfaceBrightLight = Color(0xFFFCF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFAFAFA)
val surfaceContainerLight = Color(0xFFF5F5F5)
val surfaceContainerHighLight = Color(0xFFF0F0F0)
val surfaceContainerHighestLight = Color(0xFFEBEBEB)



val primaryDark = Color(0xFFC5C0FF)
val onPrimaryDark = Color(0xFF2D2960)
val primaryContainerDark = Color(0xFF444078)
val onPrimaryContainerDark = Color(0xFFE3DFFF)
val secondaryDark = Color(0xFFC7C4DC)
val onSecondaryDark = Color(0xFF302E42)
val secondaryContainerDark = Color(0xFF464559)
val onSecondaryContainerDark = Color(0xFFE4DFF9)
val tertiaryDark = Color(0xFFEBB9D0)
val onTertiaryDark = Color(0xFF472538)
val tertiaryContainerDark = Color(0xFF603B4F)
val onTertiaryContainerDark = Color(0xFFFFD8E9)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF131318)
val onBackgroundDark = Color(0xFFE5E1E9)
val surfaceDark = Color(0xFF131318)
val onSurfaceDark = Color(0xFFE5E1E9)
val surfaceVariantDark = Color(0xFF47464F)
val onSurfaceVariantDark = Color(0xFFC8C5D0)
val outlineDark = Color(0xFF928F99)
val outlineVariantDark = Color(0xFF47464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E1E9)
val inverseOnSurfaceDark = Color(0xFF313036)
val inversePrimaryDark = Color(0xFF5C5891)
val surfaceDimDark = Color(0xFF131318)
val surfaceBrightDark = Color(0xFF3A383F)
val surfaceContainerLowestDark = Color(0xFF0E0E13)
val surfaceContainerLowDark = Color(0xFF1C1B20)
val surfaceContainerDark = Color(0xFF201F25)
val surfaceContainerHighDark = Color(0xFF2A292F)
val surfaceContainerHighestDark = Color(0xFF35343A)

